Resources:
  AppointmentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-appointment-${self:provider.stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: apt_id
          AttributeType: S
        - AttributeName: insuredId
          AttributeType: S
      KeySchema:
        - AttributeName: apt_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: InsuredIdIndex
          KeySchema:
            - AttributeName: insuredId
              KeyType: HASH
          Projection:
            ProjectionType: ALL